name: 'ryubb-github-actions-test'
description: 'test github actions'
inputs:
  notion-key:
    description: "githubのenvを通して、notion keyを送ってください。"
    required: true
  notion-database-url:
    description: "githubのenvを通して、notionのdatabase urlを送ってください。"
    required: false
  status-property:
    description: "CI実行後に変更したいステータスのプロパティ名"
    required: true
    default: "Status"
  status-value:
    description: "CI実行後に変更したいステータスを指定してください。"
    required: true
  notion-url-hook:
    description: "NotionのURLをPRの内容から取得するために、必要な文字列です。"
    required: true
    default: "#notion"
outputs:
  test-output: # id of output
    description: 'test output'
runs:
  using: 'node12'
  main: 'dist/index.js'